version: "3"
services:
  app:
    build: .
    ports:
      - "50000:5000"
    environment:
      - FLASK_APP=app.py
    networks:
      app-network:
        aliases:
          - flask-app
    command: bash -c "flask run --host=0.0.0.0 --port=5000"

  nginx:
    image: nginx:1.13.7
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    ports:
      - "80:80"

networks:
  app-network:
